config/routes.rb
Rails.application.routes.draw do
  get 'dog_shows/index'
  get 'dog_shows/show'
  get 'dog_shows/new'
  get 'dog_shows/create'
  get 'dog_shows/edit'
  get 'dog_shows/update'
  get 'dog_shows/destroy'
  get 'owners/index'
  get 'owners/show'
  get 'owners/new'
  get 'owners/create'
  get 'owners/edit'
  get 'owners/update'
  get 'owners/destroy'
  get 'breeds/index'
  get 'breeds/show'
  get 'breeds/new'
  get 'breeds/create'
  get 'breeds/edit'
  get 'breeds/update'
  get 'breeds/destroy'
  get 'static_pages/about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  # Additional routes
  resources :breeds
  resources :owners
  resources :dog_shows
  get 'about', to: 'static_pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/breed.rb
class Breed < ApplicationRecord
  has_many :breed_images
  has_many :breed_facts
  belongs_to :owner, optional: true
  has_and_belongs_to_many :dog_shows

  validates :name, presence: true, uniqueness: true
end

app/models/breed_dog_show.rb
class BreedDogShow < ApplicationRecord
  belongs_to :breed
  belongs_to :dog_show
end

app/models/breed_fact.rb
class BreedFact < ApplicationRecord
  belongs_to :breed

  validates :fact, presence: true
  validates :breed, presence: true
end

app/models/breed_image.rb
class BreedImage < ApplicationRecord
  belongs_to :breed

  validates :image_url, presence: true
  validates :breed, presence: true
end

app/models/dog_show.rb
class DogShow < ApplicationRecord
  has_and_belongs_to_many :breeds

  validates :name, presence: true
  validates :date, presence: true
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :breeds

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  def index
    @owners = Owner.all
    @breeds = if params[:search].present? && params[:owner_id].present?
                Breed.where('name LIKE ? AND owner_id = ?', "%#{params[:search]}%", params[:owner_id])
              elsif params[:search].present?
                Breed.where('name LIKE ?', "%#{params[:search]}%")
              elsif params[:owner_id].present?
                Breed.where(owner_id: params[:owner_id])
              else
                Breed.all
              end.page(params[:page]).per(10)
  end

  def show
    @breed = Breed.find(params[:id])
  end
end

app/controllers/dog_shows_controller.rb
class DogShowsController < ApplicationController
  def index
    @dog_shows = if params[:search].present?
                   DogShow.where('name LIKE ?', "%#{params[:search]}%")
                 else
                   DogShow.all
                 end.page(params[:page]).per(10)
  end

  def show
    @dog_show = DogShow.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owners = if params[:search].present?
                Owner.where('name LIKE ?', "%#{params[:search]}%")
              else
                Owner.all
              end.page(params[:page]).per(10)
  end

  def show
    @owner = Owner.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/dog_shows_helper.rb
module DogShowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/breeds/create.html.erb
<h1>Breeds#create</h1>
<p>Find me in app/views/breeds/create.html.erb</p>

app/views/breeds/destroy.html.erb
<h1>Breeds#destroy</h1>
<p>Find me in app/views/breeds/destroy.html.erb</p>

app/views/breeds/edit.html.erb
<h1>Breeds#edit</h1>
<p>Find me in app/views/breeds/edit.html.erb</p>

app/views/breeds/index.html.erb
<h1>Breeds</h1>

<%= form_with(url: breeds_path, method: :get, local: true) do %>
  <%= label_tag :search, "Search Breeds" %>
  <%= text_field_tag :search, params[:search] %>
  <%= label_tag :owner_id, "Filter by Owner" %>
  <%= select_tag :owner_id, options_from_collection_for_select(@owners, :id, :name, params[:owner_id]), include_blank: true %>
  <%= submit_tag "Search" %>
<% end %>

<%= paginate @breeds %>

<ul>
  <% @breeds.each do |breed| %>
    <li><%= link_to breed.name, breed_path(breed) %></li>
  <% end %>
</ul>

app/views/breeds/new.html.erb
<h1>Breeds#new</h1>
<p>Find me in app/views/breeds/new.html.erb</p>

app/views/breeds/show.html.erb
<h1><%= @breed.name %></h1>

<h2>Owner</h2>
<p><%= @breed.owner.name %></p>

<h2>Dog Shows</h2>
<ul>
  <% @breed.dog_shows.each do |show| %>
    <li><%= show.name %> - <%= show.date %></li>
  <% end %>
</ul>

<h2>Fun Facts</h2>
<% if @breed.breed_facts.any? %>
  <ul>
    <% @breed.breed_facts.each do |fact| %>
      <li><%= fact.fact %></li>
    <% end %>
  </ul>
<% else %>
  <p>No fun facts available for this breed.</p>
<% end %>

app/views/breeds/update.html.erb
<h1>Breeds#update</h1>
<p>Find me in app/views/breeds/update.html.erb</p>

app/views/dog_shows/create.html.erb
<h1>DogShows#create</h1>
<p>Find me in app/views/dog_shows/create.html.erb</p>

app/views/dog_shows/destroy.html.erb
<h1>DogShows#destroy</h1>
<p>Find me in app/views/dog_shows/destroy.html.erb</p>

app/views/dog_shows/edit.html.erb
<h1>DogShows#edit</h1>
<p>Find me in app/views/dog_shows/edit.html.erb</p>

app/views/dog_shows/index.html.erb
<h1>Dog Shows</h1>

<%= form_with(url: dog_shows_path, method: :get, local: true) do %>
  <%= label_tag :search, "Search Dog Shows" %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<%= paginate @dog_shows %>

<ul>
  <% @dog_shows.each do |dog_show| %>
    <li><%= dog_show.name %></li>
  <% end %>
</ul>

app/views/dog_shows/new.html.erb
<h1>DogShows#new</h1>
<p>Find me in app/views/dog_shows/new.html.erb</p>

app/views/dog_shows/show.html.erb
<h1><%= @dog_show.name %></h1>

<p><strong>Date:</strong> <%= @dog_show.date %></p>

<h2>Breeds</h2>
<ul>
  <% @dog_show.breeds.each do |breed| %>
    <li><%= link_to breed.name, breed_path(breed) %></li>
  <% end %>
</ul>

app/views/dog_shows/update.html.erb
<h1>DogShows#update</h1>
<p>Find me in app/views/dog_shows/update.html.erb</p>

app/views/home/index.html.erb
<h1>Welcome to the Dog Breeds App</h1>
<p>This is the home page.</p>

app/views/layouts/_navigation.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Breeds', breeds_path %></li>
    <li><%= link_to 'Owners', owners_path %></li>
    <li><%= link_to 'Dog Shows', dog_shows_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogBreedsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/owners/create.html.erb
<h1>Owners#create</h1>
<p>Find me in app/views/owners/create.html.erb</p>

app/views/owners/destroy.html.erb
<h1>Owners#destroy</h1>
<p>Find me in app/views/owners/destroy.html.erb</p>

app/views/owners/edit.html.erb
<h1>Owners#edit</h1>
<p>Find me in app/views/owners/edit.html.erb</p>

app/views/owners/index.html.erb
<h1>Owners</h1>

<%= form_with(url: owners_path, method: :get, local: true) do %>
  <%= label_tag :search, "Search Owners" %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<%= paginate @owners %>

<ul>
  <% @owners.each do |owner| %>
    <li><%= link_to owner.name, owner_path(owner) %></li>
  <% end %>
</ul>

app/views/owners/new.html.erb
<h1>Owners#new</h1>
<p>Find me in app/views/owners/new.html.erb</p>

app/views/owners/show.html.erb
<h1><%= @owner.name %></h1>

<h2>Breeds</h2>
<ul>
  <% @owner.breeds.each do |breed| %>
    <li><%= link_to breed.name, breed_path(breed) %></li>
  <% end %>
</ul>

app/views/owners/update.html.erb
<h1>Owners#update</h1>
<p>Find me in app/views/owners/update.html.erb</p>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>This application provides information about various dog breeds.</p>
<h2>Data Sources</h2>
<p>We use the following data sources:</p>
<ul>
  <li><a href="https://dog.ceo/dog-api/">Dog CEO API</a>: Provides information and images for various dog breeds.</li>
  <li><a href="https://rubygems.org/gems/faker">Faker Gem</a>: Used to generate random data for owners and dog shows.</li>
</ul>
<h2>ERD</h2>
<p>The database schema for this application is as follows:</p>
<img src="/assets/erd_diagram.png" alt="ERD Diagram" />